pip:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - pyyaml
  - packaging
  - tqdm
  - ipywidgets
  - jupyter
  - huggingface_hub
  - tokenizers
  - transformers
  - datasets
  - einops
  - accelerate
  - lightning
  - torchmetrics
  - optuna
  - optuna-integration[pytorch_lightning]
  - h5py #cbramod
  - lmdb
  - mne
  - ptflops
  - pyEDFlib
  - torchinfo
  - umap_learn
  - aeon #unishape
  - fastai
  - timm

torch:
  cuda: true
  cuda_index_url:  https://download.pytorch.org/whl/cu128
  minimum_version: 2.8.0
  packages:
    - torch
    - torchvision
    - torchaudio

#git:
#  repos:
#    - url: https://github.com/wjq-learning/CBraMod.git
#      branch: main
#    - url: https://github.com/qianlima-lab/UniShape.git
#      branch: main
